name: scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Every day at noon UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python scrape_jobs.py
